# 针对开发环境的docker-compose扩展文件

services:
  nest-demo:
    build:
      context: ../../apps/nest-demo
      target: development
    volumes:
      - ../../apps/nest-demo:/app
      - /app/node_modules
    ports:
      - "3100:3100"
    env_file:
      - ../env/.env.development
    depends_on:
      db:
        condition: service_healthy
